apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic-demo
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      name: logic-demo
  template:
    metadata:
      labels:
        app: backend
        name: logic-demo
    spec:
      containers:
        - name: logic-demo
          imagePullPolicy: Never
          image: logic-demo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: logic-service
spec:
  selector:
    app: backend
    name: logic-demo
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
